version: '3'
services:
  playground-web-frontend:
    image: connected-vehicle-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: connected-vehicle-backend:8080/
    ports:
      - 3000:3000
  playground-web-backend:
    image: connected-vehicle-backend:latest
    ports:
      - 8080:8080